name: teacher
description: Demonstrates how to use the flutter_plugin plugin.
publish_to: 'none'

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^2.4.1
  #日期选择
  flutter_cupertino_date_picker:
    git: https://github.com/yasseralsamman/flutter-cupertino-date-picker.git
  #多选文件
  flutterfileselector:
    git: https://gitee.com/jrnet/flutter_file_selector.git
  #
  open_file: ^3.0.1
  #图片 视频拍摄
  wechat_camera_picker: ^1.3.1
  #图片 视频选择
  wechat_assets_picker: ^4.2.2
  #缓冲视频
  cached_video_player: ^1.0.3
  #断点续传
  tus_client: ^0.0.4
  #视频缩略图
  video_thumbnail: ^0.2.5+1
  uuid: ^2.2.2
  r_scan: ^0.1.5
  #录音
  flutter_plugin_record: ^0.3.5
  #html转换
  flutter_html: ^0.11.1
  #播放音频
  audioplayers: ^0.16.2


  #file_picker:
  #  path: ../../file_picker

  dalipush:
    path: ../../dalipush_plugin

  soundpool:
    path: ../../soundpool

  video_render_plugin:
    path: ../../video_render_plugin

  video_texture_plugin:
    path: ../../video_texture_plugin

  videochat_package:
    path: ../../videochat_package

  videochat_cpp_plugin:
    path: ../../videochat_cpp_plugin


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/sdb/lastver_teacher.xml
    - assets/sdb/teacher/images/
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages



